name: Search & Update Issue Label by Unnamed
run-name: ${{github.actor}} added an issue to ${{github.repository}}
on:
  issues:
    types:
      - opened
jobs:
  error:
    if: startsWith(${{github.event.issue.title}}, 'bug' || 'bugs' || '[bug]' ) || contains(${{github.event.issue.title}}, 'bug')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify error issue"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: bug

  help:
    if: startsWith(${{github.event.issue.title}}, 'fix' || '[fix]' ) ||  contains(${{github.event.issue.title}}, 'help' || 'help needed' || 'HELP' || 'HELP NEEDED' || 'assist' || 'typo')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify help request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: help wanted

  question:
    if: startsWith(${{github.event.issue.title}}, 'question' || '[question]' ) || contains(${{github.event.issue.title}}, 'question')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify question request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: question

  feature:
    if: startsWith(${{github.event.issue.title}}, 'feature' || '[feature]', 'enhancement' || '[enhancement]' ) || contains(${{github.event.issue.title}}, 'enhancement' || 'feature')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify new feature request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: enhancement

  component:
    if: startsWith(${{github.event.issue.title}}, 'component' || '[component]' ) || contains(${{github.event.issue.title}}, 'component')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify new component request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: component
