name: Search & Update Issue Label by Unnamed
run-name: ${{github.actor}} added an issue to ${{github.repository}}
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  error:
    if: |
      startsWith(github.event.issue.title, 'bug') ||
      startsWith(github.event.issue.title, 'bugs') ||
      startsWith(github.event.issue.title, '[bug]') ||
      contains(github.event.issue.title, 'bug')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify error issue"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          is-oauth-token: true
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: bug

  help:
    if: |
      startsWith(github.event.issue.title, 'fix') ||
      startsWith(github.event.issue.title, '[fix]') ||
      contains(github.event.issue.title, 'help') ||
      contains(github.event.issue.title, 'help needed') ||
      contains(github.event.issue.title, 'HELP') ||
      contains(github.event.issue.title, 'HELP NEEDED') ||
      contains(github.event.issue.title, 'assist') ||
      contains(github.event.issue.title, 'typo')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify help request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          is-oauth-token: true
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: help wanted

  question:
    if: |
      startsWith(github.event.issue.title, 'question') ||
      startsWith(github.event.issue.title, '[question]') ||
      contains(github.event.issue.title, 'question')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify question request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          is-oauth-token: true
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: question

  feature:
    if: |
      startsWith(github.event.issue.title, 'feature') ||
      startsWith(github.event.issue.title, '[feature]') ||
      startsWith(github.event.issue.title, 'enhancement') ||
      startsWith(github.event.issue.title, '[enhancement]') ||
      contains(github.event.issue.title, 'enhancement') ||
      contains(github.event.issue.title, 'feature')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify new feature request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          is-oauth-token: true
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: enhancement

  component:
    if: |
      startsWith(github.event.issue.title, 'component') ||
      startsWith(github.event.issue.title, '[component]') ||
      contains(github.event.issue.title, 'component')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Identify new component request"
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.UNNAMED_ALERT_BOT_TOKEN }}
          is-oauth-token: true
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: component
