name: Format Codebase w/ Prettier
run-name: ${{ github.actor }} is attempting to ${{github.event_name}} to ${{github.repository}}
on:
  pull_request:
    branches:
      - main
jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ^9

  install-deps:
    runs-on: ubuntu-latest
    needs: setup-env
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

  prettier:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Runs Prettier
        run: pnpm format
