name: Format Codebase w/ Prettier
run-name: ${{ github.actor }} is attempting to make a ${{github.event_name}}.
on:
  pull_request:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ^9
      - name: Install dependencies
        run: pnpm install
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,ts,jsx,tsx,css} --tab-width 4
          prettier_plugins: "prettier-plugin-tailwindcss"
          only_changed: True
          github_token: ${{ secrets.GITHUB_TOKEN }}
