name: Format Codebase w/ Prettier
run-name: ${{ github.actor }} is attempting to ${{github.event_name}} to ${{github.repository}}
on:
  pull_request:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ^9

      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm format
