name: Linter
run-name: ${{ github.actor }} is attempting to make a ${{github.event_name}}.
on: push

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Linters
        uses: panda0603/lint-action@1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          eslint: true
          prettier: true
          auto_fix: true
          git_name: "Unnamed Lint Action"
