name: Greet New Contributor
run-name: ${{ github.actor }} icontributed to ${{github.repository}}.
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet the contributor"
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.UNNAMED_ALERT_BOT_TOKEN }}
          is-oauth-token: true
          issue-message: "Hello @contributor_name, thanks for opening your first issue. We welcome you to the ${{ github.event.repository.name }} community!"
          pr-message: "Hello @contributor_name, thanks for opening your first Pull Request. Someone will review it soon."
